name: baseline-scan
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    name: scanning app
    steps:
      - name: Checkout Main Page
        uses: actions/checkout@v4
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          Authorization: Bearer ZAP_TOKEN
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
